server.port=8080
spring.application.name=api-gateway

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:8081/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-service:8081

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90


# Rutas
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates=Path=/api/users/**

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=lb://cart-service
spring.cloud.gateway.routes[2].predicates=Path=/api/cart/**

spring.cloud.gateway.routes[3].id=product-service
spring.cloud.gateway.routes[3].uri=lb://product-service
spring.cloud.gateway.routes[3].predicates=Path=/api/products/**

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://order-service
spring.cloud.gateway.routes[4].predicates=Path=/api/orders/**


api.orders.base-path=/api/orders
api.products.base-path=/api/products
api.cart.base-path=/api/cart
api.users.base-path=/api/users
api.auth.base-path=/api/auth